//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetromMessageBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardTopic
    {
        public int ID { get; set; }
        public int BoardID { get; set; }
        public int TopicID { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
