//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetromMessageBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public short Priority { get; set; }
        public int DepartmentID { get; set; }
        public int UserID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
    }
}
