//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetromMessageBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comments = new ObservableListSource<Comment>();
            this.Topics = new ObservableListSource<Topic>();
        }
    
        public int ID { get; set; }
        public byte[] ProfilePicture { get; set; }
        public Rights Rights { get; set; }
        public Nullable<int> Score { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public int CompanyID { get; set; }
        public int DepartmentID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Comment> Comments { get; set; }
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Topic> Topics { get; set; }
    }
}
